# SPDX-FileCopyrightText: 2022-2024 CERN.
# SPDX-FileCopyrightText: 2026 TU Wien.
# SPDX-License-Identifier: MIT

[project]
name = "invenio-base"
description = "Base package for building Invenio application factories."
readme = "README.rst"
requires-python = ">=3.8"
license = "MIT"
authors = [
  { name = "CERN", email = "info@inveniosoftware.org" },
]
keywords = [
  "invenio",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
]
dependencies = [
  "blinker>=1.4",
  "flask>=3.0.0",
  "importlib-metadata>=4.4",
  "importlib-resources>=5.0",
  "itsdangerous>=2.1.0",
  "markupsafe>=0.23",
  "watchdog>2.0.0",
  "werkzeug>=3.0.0",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/inveniosoftware/invenio-base"

[project.scripts]
inveniomanage = "invenio_base.__main__:cli"

[project.entry-points."flask.commands"]
instance = "invenio_base.cli:instance"

[project.optional-dependencies]
tests = [
  "freezegun>=1.5.1",
  "pytest-black-ng>=0.4.0",
  "pytest-invenio>=1.4.2",
  "sphinx>=4.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "invenio_base/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
  "/invenio_base",
]

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D401,D202"

[tool.pytest.ini_options]
addopts = '--black --isort --pydocstyle --doctest-glob="*.rst" --doctest-modules --cov=invenio_base --cov-report=term-missing'
filterwarnings = ["ignore::pytest.PytestDeprecationWarning"]
testpaths = "tests invenio_base"
live_server_scope = "module"
